dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: weather_postgres
      user: airflow
      password: airflow
      port: 5432
      dbname: airflow
      schema: dbt
      threads: 4
      connect_timeout: 10